/* Facts from TCQ app pages/policies; US prices checked 2026-10-05. */
const TCQ_APPS = [
  {
    "id": "2tr",
    "name": "2TR: Rhythm 2 Tha Rhyme",
    "url": "https://www.tcqconsulting.org/2tr.html",
    "problemSolved": "Explore a hip-hop dictionary, find pronunciation-powered rhymes, and write lyrics privately on iPhone. No accounts, ads, or subscriptions.",
    "features": [
      "Explore a hip-hop dictionary and pronunciation-powered rhymes.",
      "Hear selected words using Apple's system speech technology.",
      "Write lyrics, save drafts, bookmark words, and revisit recent discoveries.",
      "Keep explicit dictionary and rhyme content hidden unless you choose to enable it.",
      "No accounts, advertisements, subscriptions, analytics, or tracking."
    ],
    "category": "ReferenceApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/2tr-rhythm-2-tha-rhyme/id6806783015",
    "usDownloadPrice": "2.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "2tr.html",
    "terms": [
      "rhyme",
      "rhymes",
      "rhyming",
      "lyric",
      "lyrics",
      "rap",
      "hip hop",
      "hip-hop",
      "songwriting"
    ],
    "limitation": "A dictionary and lyric workspace; not an audio recording studio.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "2tr-privacy.html",
    "icon": "assets/2tr-Icon-160.webp"
  },
  {
    "id": "herbschedule",
    "name": "Herb Schedule",
    "url": "https://www.tcqconsulting.org/herbschedule.html",
    "problemSolved": "Organize herbs and vegetables, plan care reminders, and create Away Care PDFs on iPhone with private iCloud sync.",
    "features": [
      "Organize herbs and vegetables with plant details and growing locations.",
      "Build Smart Calendars and practical care schedules.",
      "Receive reminders and review your care history.",
      "Create an Away Care PDF on your device when someone is helping.",
      "Private iCloud sync with no ads or third-party tracking."
    ],
    "category": "LifestyleApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/herb-schedule/id6804491419",
    "usDownloadPrice": "3.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "herbschedule.html",
    "terms": [
      "herb",
      "herbs",
      "garden",
      "gardening",
      "plant care",
      "plants",
      "vegetables",
      "watering"
    ],
    "limitation": "Care suggestions are prompts to check your plants and soil; no weather or location readings.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "herbschedule-privacy.html",
    "icon": "assets/herbschedule-icon-160.webp"
  },
  {
    "id": "keeptrackpro",
    "name": "KeepTrack Pro",
    "url": "https://www.tcqconsulting.org/keeptrackpro.html",
    "problemSolved": "Organize receipts, warranties, insurance, and travel documents on iPhone with local storage and optional private iCloud sync. No subscriptions.",
    "features": [
      "Keep important information organized and easy to find.",
      "Your information stays private with local storage and optional iCloud sync.",
      "No ads. No subscriptions. Built with privacy first."
    ],
    "category": "ProductivityApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.2",
    "appStoreVersionChecked": "1.0.2",
    "appStoreUrl": "https://apps.apple.com/us/app/keeptrack-pro-life-organizer/id6781452204",
    "usDownloadPrice": "0.00",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Optional in-app purchases are available.",
    "sourcePage": "keeptrackpro.html",
    "terms": [
      "receipt",
      "receipts",
      "warranty",
      "warranties",
      "insurance",
      "documents",
      "bills",
      "life organizer"
    ],
    "limitation": "Optional one-time Pro purchase unlocks additional modules.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "keeptrackpro-privacy.html",
    "icon": "assets/keeptrack-icon-160.webp"
  },
  {
    "id": "laneluck",
    "name": "LaneLuck",
    "url": "https://www.tcqconsulting.org/laneluck.html",
    "problemSolved": "Record active commutes on iPhone and review trip time, distance, speed, and timing patterns. Drive history stays on your device.",
    "features": [
      "See clear insights from your morning and evening commutes.",
      "Review drive history and identify helpful timing patterns.",
      "No ads. No subscriptions. Your drive data stays on your device."
    ],
    "category": "TravelApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.1",
    "appStoreVersionChecked": "1.0.1",
    "appStoreUrl": "https://apps.apple.com/us/app/laneluck/id6789893354",
    "usDownloadPrice": "2.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "laneluck.html",
    "terms": [
      "commute",
      "commutes",
      "commuting",
      "drive history",
      "driving time",
      "trip timing"
    ],
    "limitation": "Records active drives; location and motion permissions support recording. Not turn-by-turn navigation.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "laneluck-privacy.html",
    "icon": "assets/laneluck-icon-160.webp"
  },
  {
    "id": "macguiver",
    "name": "MacGuiver",
    "url": "https://www.tcqconsulting.org/macguiver.html",
    "problemSolved": "Match everyday materials to supported project blueprints on iPhone. Search the bundled reference offline, without accounts or cloud sync.",
    "features": [
      "Match ordinary materials with supported project blueprints.",
      "Identify the materials required for supported projects.",
      "Search the bundled material reference directly on your device.",
      "Use the app without an account, internet connection, cellular service, or iCloud.",
      "Your searches and material entries stay on your device."
    ],
    "category": "UtilitiesApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/macguiver/id6804482601",
    "usDownloadPrice": "4.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "macguiver.html",
    "terms": [
      "materials",
      "material",
      "blueprint",
      "blueprints",
      "diy",
      "workbench",
      "reverse engineer",
      "offline projects"
    ],
    "limitation": "Works offline with its bundled reference and supported project blueprints.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "macguiver-privacy.html",
    "icon": "assets/macguiver-icon-160.webp"
  },
  {
    "id": "mybagcaddie",
    "name": "My Bag Caddie",
    "url": "https://www.tcqconsulting.org/mybagcaddie.html",
    "problemSolved": "Choose golf clubs using your own yardages, shot distance, and playing conditions. My Bag Caddie calculates recommendations privately on iPhone.",
    "features": [
      "Know your club distances with confidence.",
      "Get smart club recommendations in seconds.",
      "No ads. No subscriptions. Built with golfers in mind."
    ],
    "category": "SportsApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.1",
    "appStoreVersionChecked": "1.0.1",
    "appStoreUrl": "https://apps.apple.com/us/app/mybagcaddie/id6782050091",
    "usDownloadPrice": "2.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "mybagcaddie.html",
    "terms": [
      "golf",
      "golfing",
      "golf club",
      "yardage",
      "yardages",
      "caddie",
      "club distance"
    ],
    "limitation": "Recommendations use your own club distances and the conditions you enter.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "mybagcaddie-privacy.html",
    "icon": "assets/mybagcaddie-icon-160.webp"
  },
  {
    "id": "nightdraw",
    "name": "NightDraw",
    "url": "https://www.tcqconsulting.org/nightdraw.html",
    "problemSolved": "Estimate home electricity usage and cost by room, appliance, and lighting on iPhone. Explore What If scenarios without connecting a utility account.",
    "features": [
      "Build a simple room-by-room picture of your home's energy use.",
      "Explore estimated monthly usage, cost, and helpful What If scenarios.",
      "No ads. No subscriptions. Your home energy data stays private."
    ],
    "category": "UtilitiesApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/nightdraw/id6789973877",
    "usDownloadPrice": "2.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "nightdraw.html",
    "terms": [
      "electricity",
      "electric",
      "energy bill",
      "energy cost",
      "power bill",
      "appliance",
      "appliances",
      "lights",
      "lighting"
    ],
    "limitation": "Estimates based on your entries; does not connect to a smart meter or utility account.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "nightdraw-privacy.html",
    "icon": "assets/nightdraw-icon-160.webp"
  },
  {
    "id": "packnudge",
    "name": "PackNudge",
    "url": "https://www.tcqconsulting.org/packnudge.html",
    "problemSolved": "Build reusable packing lists, check progress, and schedule departure reminders on iPhone. Works offline with private iCloud storage.",
    "features": [
      "Choose from helpful ready-made packs or create your own.",
      "Add, remove, and check off items as you prepare.",
      "Schedule gentle reminders before your departure.",
      "Track several upcoming packs and their progress in one place.",
      "Works offline with no account, advertising, analytics, or tracking.",
      "Keeps your packs private on your devices and in your iCloud account."
    ],
    "category": "TravelApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/packnudge/id6796975103",
    "usDownloadPrice": "0.00",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "packnudge.html",
    "terms": [
      "packing",
      "pack",
      "packing list",
      "suitcase",
      "passport",
      "charger",
      "luggage",
      "departure",
      "forget to bring"
    ],
    "limitation": "Packing reminders require notification permission; lists work offline with private iCloud storage.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "packnudge-privacy.html",
    "icon": "assets/packnudge-icon-160.webp"
  },
  {
    "id": "pagekey",
    "name": "PageKey",
    "url": "https://www.tcqconsulting.org/pagekey.html",
    "problemSolved": "Generate passwords on iPhone without storing them. PageKey offers automatic clipboard clearing and private on-device generation, with no subscriptions.",
    "features": [
      "Create strong, unique passwords in seconds.",
      "Everything happens privately on your device.",
      "No ads. No subscriptions. Built with privacy first."
    ],
    "category": "UtilitiesApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.1",
    "appStoreVersionChecked": "1.0.1",
    "appStoreUrl": "https://apps.apple.com/us/app/pagekey/id6772603381",
    "usDownloadPrice": "0.00",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Optional in-app purchases are available.",
    "sourcePage": "pagekey.html",
    "terms": [
      "password",
      "passwords",
      "password generator",
      "clipboard"
    ],
    "limitation": "Generates passwords without storing them; optional packs and Complete bundle purchases. Not a password vault.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "pagekey-privacy.html",
    "icon": "assets/pagekey-icon-160.webp"
  },
  {
    "id": "platecrib",
    "name": "Plate Crib",
    "url": "https://www.tcqconsulting.org/platecrib.html",
    "problemSolved": "Score license-plate characters, play classic cribbage against the CPU, or learn in Practice Mode on iPhone. No camera or location access required.",
    "features": [
      "Turn visible license-plate characters into a quick cribbage score.",
      "Play classic cribbage against the CPU.",
      "Learn the game with a dedicated Practice Mode.",
      "Continue saved Classic and Practice games on your device.",
      "No account, location, camera, advertising, or tracking required."
    ],
    "category": "GameApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/plate-crib/id6804400155",
    "usDownloadPrice": "0.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "platecrib.html",
    "terms": [
      "cribbage",
      "crib",
      "license plate",
      "license plates",
      "number plate"
    ],
    "limitation": "Plate characters are entered manually; no camera scanning or vehicle lookup.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "platecrib-privacy.html",
    "icon": "assets/platecrib-icon-160.webp"
  },
  {
    "id": "rememberthisday",
    "name": "Remember This Day",
    "url": "https://www.tcqconsulting.org/rememberthisday.html",
    "problemSolved": "Write meaningful memories and set date-based or annual reminders on iPhone, with private iCloud sync and no accounts or advertising.",
    "features": [
      "Write and keep meaningful memories in one calm space.",
      "Choose a date to be reminded of each memory.",
      "Repeat important reminders every year.",
      "Sync privately through your personal iCloud account.",
      "No accounts, advertising, analytics, or tracking."
    ],
    "category": "LifestyleApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/remember-this-day-memories/id6804475882",
    "usDownloadPrice": "0.00",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "rememberthisday.html",
    "terms": [
      "annual",
      "anniversary",
      "anniversaries",
      "birthday",
      "birthdays",
      "yearly",
      "yearly reminders",
      "memory reminder"
    ],
    "limitation": "Written memories with date-based reminders; notifications require permission. Private iCloud sync.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "rememberthisday-privacy.html",
    "icon": "assets/rememberthisday-icon-160.webp"
  },
  {
    "id": "snapstreak",
    "name": "SnapStreak",
    "url": "https://www.tcqconsulting.org/snapstreak.html",
    "problemSolved": "Play family-friendly photo scavenger hunts on iPhone. Choose location packs, difficulty, and an optional timer, without accounts or photo uploads.",
    "features": [
      "Explore location packs filled with family-friendly photo challenges.",
      "Choose your difficulty and add an optional timer for extra pressure.",
      "Play privately with no account, advertising, analytics, or photo uploads."
    ],
    "category": "GameApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/snapstreak-scavenger-hunt/id6797031133",
    "usDownloadPrice": "0.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "snapstreak.html",
    "terms": [
      "scavenger",
      "scavenger hunt",
      "photo hunt",
      "photo challenges",
      "family game",
      "photography game"
    ],
    "limitation": "Photo scavenger hunts with location packs; no accounts or photo uploads.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "snapstreak-privacy.html",
    "icon": "assets/snapstreak-icon-160.webp"
  },
  {
    "id": "stamped",
    "name": "Stamped",
    "url": "https://www.tcqconsulting.org/stamped.html",
    "problemSolved": "Keep a private journal of places, meals, drinks, and experiences on iPhone, with optional iCloud sync. No ads or subscriptions.",
    "features": [
      "Capture the places, meals, drinks, and moments you'll always want to remember.",
      "Your memories stay private on your device with optional iCloud sync.",
      "No ads. No subscriptions. Built with privacy first."
    ],
    "category": "LifestyleApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.1",
    "appStoreVersionChecked": "1.0.1",
    "appStoreUrl": "https://apps.apple.com/us/app/stamped-would-i-do-this-again/id6787419780",
    "usDownloadPrice": "2.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "stamped.html",
    "terms": [
      "journal",
      "journaling",
      "restaurants",
      "restaurant",
      "meals",
      "drinks",
      "experiences",
      "places visited"
    ],
    "limitation": "A personal journal with optional private iCloud sync; not a booking service.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "stamped-privacy.html",
    "icon": "assets/stamped-icon-160.webp"
  },
  {
    "id": "sumofnone",
    "name": "Sum Of None",
    "url": "https://www.tcqconsulting.org/sumofnone.html",
    "problemSolved": "Bring a number matrix to zero with Guided Practice, three difficulty levels, and a Daily Matrix. Play privately on iPhone without accounts or ads.",
    "features": [
      "Choose Easy, Medium, or Hard puzzles and solve at your own pace.",
      "Learn the rules with Guided Practice and return for a new Daily Matrix.",
      "Resume unfinished games and track up to 50 personal best scores on your device.",
      "No accounts, advertisements, analytics, or cloud synchronization."
    ],
    "category": "GameApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.0",
    "appStoreVersionChecked": "1.0.0",
    "appStoreUrl": "https://apps.apple.com/us/app/sum-of-none/id6796989977",
    "usDownloadPrice": "0.00",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "sumofnone.html",
    "terms": [
      "number puzzle",
      "number puzzles",
      "matrix",
      "zero",
      "logic puzzle",
      "math puzzle",
      "daily puzzle",
      "brain teaser"
    ],
    "limitation": "Local saved games and personal scores; no online leaderboards or cloud sync.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "sumofnone-privacy.html",
    "icon": "assets/sumofnone-icon-160.webp"
  },
  {
    "id": "verdial",
    "name": "Verdial",
    "url": "https://www.tcqconsulting.org/verdial.html",
    "problemSolved": "Organize brand assets, create visuals, prepare captions and hashtags, and plan content on iPhone. Share finished work only when you choose.",
    "features": [
      "Keep brand colors, product details, assets, captions, and hashtags organized.",
      "Create images and multi-image projects in one focused workspace.",
      "Plan content, prepare drafts, and keep a useful post history.",
      "Hand finished content to the social platform you choose when you are ready.",
      "No advertising or cross-app tracking. Your creative workspace stays under your control."
    ],
    "category": "ProductivityApplication",
    "operatingSystem": "iOS 17.6 or later",
    "websiteVersion": "1.0.3",
    "appStoreVersionChecked": "1.0.3",
    "appStoreUrl": "https://apps.apple.com/us/app/verdial/id6802049440",
    "usDownloadPrice": "6.99",
    "currency": "USD",
    "priceChecked": "2026-10-05",
    "purchaseNote": "Check the listing for any optional in-app purchases.",
    "sourcePage": "verdial.html",
    "terms": [
      "marketing",
      "brand",
      "branding",
      "captions",
      "caption",
      "hashtags",
      "content plan",
      "social media",
      "instagram"
    ],
    "limitation": "Prepares content for you to share; does not automatically publish to social platforms.",
    "reviewed": "2026-10-05",
    "sourcePolicy": "verdial-privacy.html",
    "icon": "assets/verdial-icon-160.webp"
  }
];
if (typeof module !== "undefined") module.exports = TCQ_APPS;
